---
dist: bionic
sudo: required
group: edge
services: docker
language: python
python: 3.8
env:
  - SCENERIO=default
install: pip install ansible 'molecule[docker]' molecule docker pre-commit pylint pep257 yamllint ansible-lint
script:
  - pushd .. && ln -s ansible-drupalvm pacifica.ansible_drupalvm && popd
  - travis_wait 60 molecule test -s $SCENERIO
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
