- name: RedHat 8 Fixes
  block:
    - name: Fix Ansible Package Names
      lineinfile:
        path: "{{ drupalvm_dir }}/provisioning/tasks/init-RedHat.yml"
        regexp: 'python.*-pycurl'
        line: '    - python3-pycurl'

    - name: Fix Varnish Package Names
      lineinfile:
        path: "{{ drupalvm_dir }}/provisioning/roles/geerlingguy.varnish/tasks/setup-RedHat.yml"
        regexp: 'pygpgme'
        line: '      - python3-gpg'

    - name: Fix RHEL 7+ isms
      replace:
        regexp: " == '7'"
        replace: " >= '7'"
        path: "{{ drupalvm_dir }}/provisioning/roles/geerlingguy.solr/tasks/install.yml"
  when:
    - ansible_distribution_version.split(".")[0] >= '8'