---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint . && ansible-lint
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: ansible
