---
- name: Verify
  hosts: all
  vars:
    drupalvm_version: '6.0.0'
    drupalvm_dir: "/etc/ansible/drupal-vm-{{ drupalvm_version }}"
  pre_tasks:
    - name: Fix Docker hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^::1'
        state: absent
        unsafe_writes: yes
    - name: Drop Docker Compatible Config
      copy:
        content: |
          hostname_configure: false
          firewall_enabled: false
          installed_extras:
            - adminer
            - drush
            - mailhog
            - pimpmylog
            - solr
          drupal_build_makefile: false
          drupal_build_composer: false
          drupal_build_composer_project: false
          drupal_install_site: false
        dest: "{{ drupalvm_dir }}/local.config.yml"
    - name: Update Debian Cache
      apt:
        name: curl
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Try running Drupal VM
      command: "ansible-playbook {{ drupalvm_dir }}/provisioning/playbook.yml"
      changed_when: false
  tasks:
    - name: Stat Drupal VM Directory
      stat:
        path: "{{ drupalvm_dir }}"
      register: st
    - name: Test Drupal VM Directory
      assert:
        that:
          - st.stat.isdir is defined and st.stat.isdir
    - name: Stat Pacifica Directory
      stat:
        path: "{{ drupalvm_dir }}/provisioning/roles/pacifica.ansible_pacifica"
      register: st
    - name: Test Pacifica Directory
      assert:
        that:
          - st.stat.isdir is defined and st.stat.isdir